# Generated by Django 2.0.12 on 2020-01-21 11:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('small_small_hr', '0007_auto_20190625_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualleave',
            name='year',
            field=models.PositiveIntegerField(choices=[(2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], db_index=True, default=2017, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='A square image works best', max_length=255, upload_to='profile_pics', verbose_name='Profile Image'),
        ),
    ]
