# Generated by Django 2.2 on 2020-01-19 09:17

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('small_small_hr', '0008_auto_20200119_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='A square image works best', max_length=255, upload_to='profile_pics', verbose_name='Profile Image'),
        ),
    ]
