# Generated by Django 2.0.12 on 2020-01-21 12:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('small_small_hr', '0009_myprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyProfile',
            new_name='Profile',
        ),
    ]
