# Generated by Django 2.2 on 2020-01-21 04:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('small_small_hr', '0011_auto_20200119_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Data'),
        ),
    ]
